# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_video_terms_accepted_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='geo_point',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
